const fs = require('fs');
const P = 'E:\\MarkdownNote\\src\\renderer\\editor.js';
let src = fs.readFileSync(P, 'utf-8');
let n = 0;
const rep = (oldL, newL, label) => {
  const o = oldL.join('\n'), x = newL.join('\n');
  if (!src.includes(o)) { console.error('NOT FOUND: ' + label); process.exit(1); }
  src = src.replace(o, x); n++;
};

// 1) require hljs
rep(
["const pasteImage = require('./paste-image');"],
["const pasteImage = require('./paste-image');",
"const hljs = require('highlight.js');"],
'require hljs'
);

// 2) ensureCodeToolbar: drop the lang label (moved to bottom-right picker)
rep(
["  const lang = codeLangOf(pre);",
"  if (lang) {",
"    const label = document.createElement('span');",
"    label.className = 'code-lang-label';",
"    label.textContent = lang;",
"    bar.appendChild(label);",
"  }",
"  const btn = document.createElement('button');"],
["  const btn = document.createElement('button');"],
'toolbar no label'
);

// 3) add language picker + highlight + menu helpers after refreshToolbar
rep(
["function refreshToolbar(pre) {",
"  const btn = pre.querySelector(':scope > .code-toolbar .code-ln-btn');",
"  if (btn) btn.classList.toggle('active', !!pre.querySelector(':scope > .code-gutter'));",
"}"],
["function refreshToolbar(pre) {",
"  const btn = pre.querySelector(':scope > .code-toolbar .code-ln-btn');",
"  if (btn) btn.classList.toggle('active', !!pre.querySelector(':scope > .code-gutter'));",
"}",
"",
"// ---------- 代码语言：右下角选择器 + 编辑实时高亮（WYSIWYG 式） ----------",
"const CODE_LANGS = [",
"  ['js', 'JavaScript'], ['ts', 'TypeScript'], ['py', 'Python'], ['java', 'Java'],",
"  ['c', 'C'], ['cpp', 'C++'], ['cs', 'C#'], ['go', 'Go'], ['rs', 'Rust'],",
"  ['rb', 'Ruby'], ['php', 'PHP'], ['swift', 'Swift'], ['kt', 'Kotlin'],",
"  ['sql', 'SQL'], ['html', 'HTML'], ['css', 'CSS'], ['json', 'JSON'],",
"  ['xml', 'XML'], ['yaml', 'YAML'], ['toml', 'TOML'], ['bash', 'Bash'],",
"  ['sh', 'Shell'], ['md', 'Markdown'], ['diff', 'Diff'], ['ini', 'INI'],",
"  ['properties', 'Properties'], ['dockerfile', 'Dockerfile'], ['makefile', 'Makefile'],",
"  ['lua', 'Lua'], ['perl', 'Perl'], ['r', 'R'], ['dart', 'Dart']",
"];",
"",
"function escapeHtml(s) {",
"  return String(s == null ? '' : s)",
"    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')",
"    .replace(/\"/g, '&quot;');",
"}",
"",
"// 重建代码高亮（不改变文本内容，只包 <span class=\"hljs-*\">），保持光标位置",
"function highlightCodeBlock(pre) {",
"  const code = pre.querySelector('code');",
"  if (!code) return;",
"  const lang = codeLangOf(pre);",
"  const sel = window.getSelection();",
"  let keep = -1;",
"  if (sel && sel.rangeCount > 0) {",
"    const range = sel.getRangeAt(0);",
"    const sn = range.startContainer;",
"    if (code.contains(sn)) {",
"      const preRange = document.createRange();",
"      preRange.selectNodeContents(code);",
"      preRange.setEnd(sn, range.startOffset);",
"      const before = preRange.toString();",
"      let zw = 0;",
"      for (const ch of before) if (ch === ZWSP) zw++;",
"      keep = before.length - zw;",
"    }",
"  }",
"  const raw = (code.textContent || '').replace(/\\u200b/g, '');",
"  let html = '';",
"  if (lang && hljs.getLanguage(lang)) {",
"    try { html = hljs.highlight(raw, { language: lang, ignoreIllegals: true }).value; }",
"    catch (err) { html = escapeHtml(raw); }",
"  } else {",
"    html = escapeHtml(raw);",
"  }",
"  code.innerHTML = html;",
"  if (!code.textContent) code.appendChild(document.createTextNode(ZWSP));",
"  if (keep >= 0) placeCaretAtOffset(code, Math.min(keep, (code.textContent || '').length));",
"}",
"",
"let highlightTimer = null;",
"function scheduleHighlight(pre) {",
"  clearTimeout(highlightTimer);",
"  highlightTimer = setTimeout(() => {",
"    highlightTimer = null;",
"    if (pre && pre.isConnected) highlightCodeBlock(pre);",
"  }, 260);",
"}",
"",
"function setCodeLang(pre, lang) {",
"  const code = pre.querySelector('code');",
"  if (!code) return;",
"  if (lang) code.className = 'language-' + lang;",
"  else code.removeAttribute('class');",
"  updateLangPicker(pre);",
"  highlightCodeBlock(pre);",
"  scheduleSerialize();",
"}",
"",
"function codeLangName(pre) {",
"  const l = codeLangOf(pre);",
"  return l || 'text';",
"}",
"",
"function updateLangPicker(pre) {",
"  const picker = pre.querySelector(':scope > .code-lang-picker');",
"  if (picker) picker.textContent = codeLangName(pre);",
"}",
"",
"function ensureCodeLangPicker(pre) {",
"  if (pre.querySelector(':scope > .code-lang-picker')) {",
"    updateLangPicker(pre);",
"    return;",
"  }",
"  const btn = document.createElement('button');",
"  btn.type = 'button';",
"  btn.className = 'code-lang-picker';",
"  btn.setAttribute('contenteditable', 'false');",
"  btn.textContent = codeLangName(pre);",
"  btn.title = '选择代码语言';",
"  btn.addEventListener('mousedown', (e) => e.preventDefault());",
"  btn.addEventListener('click', (e) => {",
"    e.preventDefault();",
"    e.stopPropagation();",
"    showLangMenu(pre, btn);",
"  });",
"  pre.appendChild(btn);",
"}",
"",
"let langMenuEl = null;",
"let langMenuPre = null;",
"function buildLangMenu() {",
"  if (langMenuEl) return langMenuEl;",
"  const menu = document.createElement('div');",
"  menu.className = 'code-lang-menu';",
"  menu.setAttribute('contenteditable', 'false');",
"  const input = document.createElement('input');",
"  input.className = 'code-lang-input';",
"  input.placeholder = '输入语言名，回车应用';",
"  input.spellcheck = false;",
"  const list = document.createElement('div');",
"  list.className = 'code-lang-list';",
"  menu.appendChild(input);",
"  menu.appendChild(list);",
"  menu.hidden = true;",
"  document.body.appendChild(menu);",
"  langMenuEl = menu;",
"  const render = () => {",
"    const q = input.value.trim().toLowerCase();",
"    const items = CODE_LANGS.filter(([k]) => !q || k.indexOf(q) !== -1 || k === q || (q && k.startsWith(q)));",
"    list.textContent = '';",
"    for (const [k, name] of items) {",
"      const b = document.createElement('button');",
"      b.type = 'button';",
"      b.className = 'code-lang-item';",
"      b.textContent = name;",
"      b.dataset.lang = k;",
"      b.addEventListener('mousedown', (e) => e.preventDefault());",
"      b.addEventListener('click', () => {",
"        if (langMenuPre) setCodeLang(langMenuPre, k);",
"        hideLangMenu();",
"      });",
"      list.appendChild(b);",
"    }",
"  };",
"  input.addEventListener('input', render);",
"  input.addEventListener('keydown', (e) => {",
"    if (e.key === 'Enter') {",
"      e.preventDefault();",
"      const q = input.value.trim().toLowerCase();",
"      const first = list.querySelector('.code-lang-item');",
"      const lang = first ? first.dataset.lang : (q || '');",
"      if (langMenuPre && lang) setCodeLang(langMenuPre, lang);",
"      hideLangMenu();",
"    } else if (e.key === 'Escape') {",
"      hideLangMenu();",
"    }",
"    e.stopPropagation();",
"  });",
"  render();",
"  return menu;",
"}",
"",
"function showLangMenu(pre, btn) {",
"  const menu = buildLangMenu();",
"  langMenuPre = pre;",
"  const input = menu.querySelector('.code-lang-input');",
"  input.value = codeLangName(pre) === 'text' ? '' : codeLangName(pre);",
"  input.dispatchEvent(new Event('input'));",
"  menu.hidden = false;",
"  const rect = btn.getBoundingClientRect();",
"  menu.style.left = Math.max(8, Math.min(rect.left, window.innerWidth - 240)) + 'px';",
"  const h = Math.min(320, menu.offsetHeight || 320);",
"  menu.style.top = (rect.bottom + 4 > window.innerHeight - h ? rect.top - h - 4 : rect.bottom + 4) + 'px';",
"  input.focus();",
"}",
"",
"function hideLangMenu() {",
"  if (langMenuEl) langMenuEl.hidden = true;",
"  langMenuPre = null;",
"}",
"",
"function onDocClickForLangMenu(e) {",
"  if (langMenuEl && !langMenuEl.hidden && langMenuEl !== e.target && !langMenuEl.contains(e.target)) {",
"    hideLangMenu();",
"  }",
"}"],
'lang picker helpers'
);

// 4) onInput: schedule highlight for current code block
rep(
["  pendingInputTimer = setTimeout(() => {",
"    if (tryEmptyMarker()) { scheduleSerialize(); return; }",
"    if (tryInlineFormat()) { scheduleSerialize(); return; }",
"    syncCodeGutters();",
"    scheduleSerialize();",
"  }, 0);"],
["  const node = caretNode();",
"  const inPre = node ? closestTag(node, 'pre') : null;",
"  if (inPre) scheduleHighlight(inPre);",
"  pendingInputTimer = setTimeout(() => {",
"    if (tryEmptyMarker()) { scheduleSerialize(); return; }",
"    if (tryInlineFormat()) { scheduleSerialize(); return; }",
"    syncCodeGutters();",
"    scheduleSerialize();",
"  }, 0);"],
'onInput highlight'
);

// 5) compositionend: highlight too
rep(
["  pane.addEventListener('compositionend', () => {",
"    composing = false;",
"    scheduleSerialize(100);",
"  });"],
["  pane.addEventListener('compositionend', () => {",
"    composing = false;",
"    const node = caretNode();",
"    const pre = node ? closestTag(node, 'pre') : null;",
"    if (pre) scheduleHighlight(pre);",
"    scheduleSerialize(100);",
"  });"],
'compositionend highlight'
);

// 6) document click to close lang menu (in init)
rep(
["  pane.addEventListener('paste', onPaste);",
"}",
"",
"function load(content) {"],
["  pane.addEventListener('paste', onPaste);",
"  document.addEventListener('click', onDocClickForLangMenu, true);",
"}",
"",
"function load(content) {"],
'init doc click'
);

// 7) load(): ensure lang picker on every pre
rep(
["  for (const pre of pane.querySelectorAll('pre')) {",
"    ensureCodeToolbar(pre);",
"    if (codeLinesEnabled) addCodeGutter(pre);",
"  }"],
["  for (const pre of pane.querySelectorAll('pre')) {",
"    ensureCodeToolbar(pre);",
"    ensureCodeLangPicker(pre);",
"    if (codeLinesEnabled) addCodeGutter(pre);",
"  }"],
'load lang picker'
);

// 8) startCodeFence: ensure lang picker
rep(
["  pre.appendChild(code);",
"  ensureCodeToolbar(pre);",
"  if (codeLinesEnabled) addCodeGutter(pre);"],
["  pre.appendChild(code);",
"  ensureCodeToolbar(pre);",
"  ensureCodeLangPicker(pre);",
"  if (codeLinesEnabled) addCodeGutter(pre);"],
'startCodeFence lang picker'
);

fs.writeFileSync(P, src, 'utf-8');
console.log('editor.js patched (' + n + ' hunks)');
